// Business Configuration
// Generated by: genesis new
// Date: 2025-10-20T13:02:09.253Z

/**
 * Business Information
 * 
 * This file contains business-specific configuration.
 * Update this file to change business details across the site.
 */

export interface BusinessConfig {
  name: string;
  tagline: string;
  industry: string;
  businessType: string;
  
  contact: {
    phone: string;
    email: string;
    address: {
      street: string;
      city: string;
      state: string;
      zip: string;
      country: string;
    };
  };
  
  branding: {
    colorScheme: string;
    colors: {
      primaryDark: string;
      primaryMedium: string;
      primaryLight: string;
      accentPrimary: string;
      accentSecondary: string;
      textPrimary: string;
      textSecondary: string;
      textTertiary: string;
    };
  };
  
  seo: {
    description: string;
    keywords: string[];
  };
  
  social: {
    facebook?: string;
    twitter?: string;
    instagram?: string;
    linkedin?: string;
  };
}

export const businessConfig: BusinessConfig = {
  name: "Dominguez Tech Solutions",
  tagline: "Reliable Moving Company throughout Oklahoma",
  industry: "logistics",
  businessType: "Moving Company",
  
  contact: {
    phone: "555-555-5555",
    email: "email@business.com",
    address: {
      street: "509 Southeast Grand Blvd",
      city: "Oklahoma City",
      state: "Oklahoma",
      zip: "73129",
      country: "United States"
    }
  },
  
  branding: {
    colorScheme: "Retail Vibrant",
    colors: {
      primaryDark: "#be123c",
      primaryMedium: "#e11d48",
      primaryLight: "#f43f5e",
      accentPrimary: "#fb7185",
      accentSecondary: "#fda4af",
      textPrimary: "#fff1f2",
      textSecondary: "#ffe4e6",
      textTertiary: "#fecdd3"
    }
  },
  
  seo: {
    description: "Dominguez Tech Solutions - Professional Moving Company services in Oklahoma City, Oklahoma. Contact us at (555) 555-5555.",
    keywords: ["moving company","oklahoma city","oklahoma","logistics","moving company","freight services","last-mile delivery","courier services","logistics provider"]
  },
  
  social: {
    // Add your social media URLs here
    // facebook: "https://facebook.com/yourbusiness",
    // twitter: "https://twitter.com/yourbusiness",
    // instagram: "https://instagram.com/yourbusiness",
    // linkedin: "https://linkedin.com/company/yourbusiness"
  }
};

export default businessConfig;
