// Business Configuration
// Generated by: genesis new
// Date: 2025-10-19T18:48:38.834Z

/**
 * Business Information
 * 
 * This file contains business-specific configuration.
 * Update this file to change business details across the site.
 */

export interface BusinessConfig {
  name: string;
  tagline: string;
  industry: string;
  businessType: string;
  
  contact: {
    phone: string;
    email: string;
    address: {
      street: string;
      city: string;
      state: string;
      zip: string;
      country: string;
    };
  };
  
  branding: {
    colorScheme: string;
    colors: {
      primaryDark: string;
      primaryMedium: string;
      primaryLight: string;
      accentPrimary: string;
      accentSecondary: string;
      textPrimary: string;
      textSecondary: string;
      textTertiary: string;
    };
  };
  
  seo: {
    description: string;
    keywords: string[];
  };
  
  social: {
    facebook?: string;
    twitter?: string;
    instagram?: string;
    linkedin?: string;
  };
}

export const businessConfig: BusinessConfig = {
  name: "New Business",
  tagline: "Quality products and service in oklahoma city",
  industry: "retail",
  businessType: "Marketplace",
  
  contact: {
    phone: "555 123-4444",
    email: "email@email.com",
    address: {
      street: "420 sw 34th street",
      city: "oklahoma city",
      state: "oklahoma",
      zip: "73127",
      country: "United States"
    }
  },
  
  branding: {
    colorScheme: "Retail Vibrant",
    colors: {
      primaryDark: "#be123c",
      primaryMedium: "#e11d48",
      primaryLight: "#f43f5e",
      accentPrimary: "#fb7185",
      accentSecondary: "#fda4af",
      textPrimary: "#fff1f2",
      textSecondary: "#ffe4e6",
      textTertiary: "#fecdd3"
    }
  },
  
  seo: {
    description: "New Business - Professional Marketplace services in oklahoma city, oklahoma. Contact us at (555) 123-4444.",
    keywords: ["marketplace","oklahoma city","oklahoma","retail","boutique","general store","specialty shop","e-commerce","marketplace"]
  },
  
  social: {
    // Add your social media URLs here
    // facebook: "https://facebook.com/yourbusiness",
    // twitter: "https://twitter.com/yourbusiness",
    // instagram: "https://instagram.com/yourbusiness",
    // linkedin: "https://linkedin.com/company/yourbusiness"
  }
};

export default businessConfig;
