// new-site - Deno Genesis Site Configuration
// Generated by genesis init command
// This file configures your site's specific settings

export interface SiteConfig {
  name: string;
  port: number;
  description: string;
  template: string;
  features: string[];
  paths: {
    public: string;
    pages: string;
    styles: string;
    scripts: string;
    images: string;
  };
}

export const siteConfig: SiteConfig = {
  name: "new-site",
  port: 3001,
  description: "Deno Genesis Site",
  template: "basic",
  features: [
    "responsive-design",
    "seo-optimized", 
    "accessibility-ready",
    "performance-optimized"
  ],
  paths: {
    public: "./public",
    pages: "./public/pages",
    styles: "./public/styles", 
    scripts: "./public/scripts",
    images: "./public/images"
  }
};

// Export for use in main.ts and other modules
export default siteConfig;
