// Business Configuration
// Generated by: genesis new
// Date: 2025-10-19T10:53:53.923Z

/**
 * Business Information
 * 
 * This file contains business-specific configuration.
 * Update this file to change business details across the site.
 */

export interface BusinessConfig {
  name: string;
  tagline: string;
  industry: string;
  businessType: string;
  
  contact: {
    phone: string;
    email: string;
    address: {
      street: string;
      city: string;
      state: string;
      zip: string;
      country: string;
    };
  };
  
  branding: {
    colorScheme: string;
    colors: {
      primaryDark: string;
      primaryMedium: string;
      primaryLight: string;
      accentPrimary: string;
      accentSecondary: string;
      textPrimary: string;
      textSecondary: string;
      textTertiary: string;
    };
  };
  
  seo: {
    description: string;
    keywords: string[];
  };
  
  social: {
    facebook?: string;
    twitter?: string;
    instagram?: string;
    linkedin?: string;
  };
}

export const businessConfig: BusinessConfig = {
  name: "New Business",
  tagline: "Professional Home Building serving Oklahoma City",
  industry: "construction",
  businessType: "Home Building",
  
  contact: {
    phone: "405-861-7960",
    email: "contact@email.com",
    address: {
      street: "426 SW 45th Street OKC OK 73128",
      city: "Oklahoma City",
      state: "OK",
      zip: "73128",
      country: "United States"
    }
  },
  
  branding: {
    colorScheme: "Industrial Blue",
    colors: {
      primaryDark: "#0d1b2a",
      primaryMedium: "#1b263b",
      primaryLight: "#415a77",
      accentPrimary: "#778da9",
      accentSecondary: "#e76f51",
      textPrimary: "#f1f5f9",
      textSecondary: "#cbd5e1",
      textTertiary: "#94a3b8"
    }
  },
  
  seo: {
    description: "New Business - Professional Home Building services in Oklahoma City, OK. Contact us at (405) 861-7960.",
    keywords: ["home building","oklahoma city","ok","construction","general contractor","roofing contractor","remodeling","home building","commercial construction"]
  },
  
  social: {
    // Add your social media URLs here
    // facebook: "https://facebook.com/yourbusiness",
    // twitter: "https://twitter.com/yourbusiness",
    // instagram: "https://instagram.com/yourbusiness",
    // linkedin: "https://linkedin.com/company/yourbusiness"
  }
};

export default businessConfig;
